# Generated by Django 5.1.1 on 2025-10-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=models.CharField(
                choices=[("HTG", "Haitian Gourdes (HTG)"), ("USD", "US Dollars (USD)")],
                default="HTG",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
    ]
